### ISSUE TITLE
before_worker_boot failed with exception (ArgumentError)  using Sidekiq v7 on embedded mode

### ISSUE THREAD

**Issue by eddygarcas** [sidekiq-cron/sidekiq-cron#387]
Ruby version: 3.1.2
Rails version: "~> 7.0.3"
Sidekiq / Pro / Enterprise version(s): 7.0.1
Sidekiq-cron: master

Hi, hope you can advice me on this.
I'm currently using the latest Sidekiq 7 on embedded mode as i don't what to run multiple sidekiq instances on the same app.

Following the steps described [here](https://github.com/mperham/sidekiq/wiki/Embedding#puma) to enabled embedded mode on a Puma server and running docker I've got this trace:
```
12:27:45 web.1  | [8353] ! WARNING: Detected running cluster mode with 1 worker.
12:27:45 web.1  | [8353] ! Running Puma in cluster mode with a single worker is often a misconfiguration.
12:27:45 web.1  | [8353] ! Consider running Puma in single-mode (workers = 0) in order to reduce memory overhead.
12:27:45 web.1  | [8353] ! Set the `silence_single_worker_warning` option to silence this warning message.
12:27:45 web.1  | DEBUGGER: Attaching after process 8353 fork to child process 8364
12:27:45 web.1  | Subprocess Debugger (ruby-debug-ide 0.7.3, debase 0.2.5.beta2, file filtering is supported) listens on 0.0.0.0:36159
12:28:45 web.1  | [8353] ! Terminating timed out worker (worker failed to boot within 60 seconds): 8364
12:28:45 web.1  | DEBUGGER[bin/rails#8441]: Attaching after process 8353 fork to child process 8441
12:28:45 web.1  | Subprocess Debugger (ruby-debug-ide 0.7.3, debase 0.2.5.beta2, file filtering is supported) listens on 0.0.0.0:43215
12:29:14 web.1  | [8441] WARNING hook before_worker_boot failed with exception (ArgumentError) wrong number of arguments (given 2, expected 1)
```
I've added an issue in Sidekiq but seems that the issue relies on Sidekiq-cron, as per following trace:

```
/3.1.0/bundler/gems/sidekiq-cron-70ce5c57ab36/lib/sidekiq/cron/launcher.rb:17:in 'initialize'
/3.1.0/gems/sidekiq-7.0.1/lib/sidekiq/embedded.rb:16:in 'new'
/3.1.0/gems/sidekiq-7.0.1/lib/sidekiq/embedded.rb:16:in 'run' config/puma.rb:50:in 'block in _load_from'
/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:297:in 'block in run_hooks'
/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:295:in 'each'
/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:295:in 'run_hooks'
/3.1.0/gems/puma-5.6.5/lib/puma/cluster/worker.rb:55:in 'run'
/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:204:in 'worker'
```

Any advice would be much appreciate it.
Thanks

**Comment by rromanchuk** [comment]
@eddygarcas I "fixed-to-just-get-running-again" https://github.com/rromanchuk/sidekiq-cron/pull/2


```ruby
# config/puma/production.rb
workers 2
preload_app!


x = nil
on_worker_boot do
  puts "on_worker_boot"
  x = Sidekiq.configure_embed do |config|
    config.logger.level = Logger::DEBUG
    config.queues = %w[default low]
    config.concurrency = 1
    config.on(:startup) do
      puts "on startup"
      schedule_file = "config/schedule.yml"
      if File.exist?(schedule_file)
        Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
      end
    end
  end
  x.run
end

on_worker_shutdown do
  puts "on_worker_shutdown"
  x&.stop
end

```

**Comment by eddygarcas** [comment]
Thanks for the introduction @markets :-)
The embedded mode it's great to reuse one of the Puma server thread to run sidekiq on there, this way I can encapsulate simple functionality without creating a whole sidekiq instance for it.

@rromanchuk you fix worked beautifully thanks! here the trace I've got:
```

app_1       | [12] Puma starting in cluster mode...
app_1       | [12] * Puma version: 6.0.0 (ruby 3.1.2-p20) ("Sunflower")
app_1       | [12] *  Min threads: 1
app_1       | [12] *  Max threads: 4
app_1       | [12] *  Environment: development
app_1       | [12] *   Master PID: 12
app_1       | [12] *      Workers: 1
app_1       | [12] *     Restarts: (✔) hot (✖) phased
app_1       | [12] * Preloading application
app_1       | [12] * Listening on http://0.0.0.0:3000
app_1       | [12] Use Ctrl-C to stop
app_1       | [12] ! WARNING: Detected running cluster mode with 1 worker.
app_1       | [12] ! Running Puma in cluster mode with a single worker is often a misconfiguration.
app_1       | [12] ! Consider running Puma in single-mode (workers = 0) in order to reduce memory overhead.
app_1       | [12] ! Set the `silence_single_worker_warning` option to silence this warning message.
app_1       | on_worker_boot
app_1       | 2022-12-14T08:27:04.439Z pid=15 tid=2mr INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-musl]
app_1       | 2022-12-14T08:27:04.439Z pid=15 tid=2mr INFO: Sidekiq Pro 7.0.4, commercially licensed. Thanks for your support!
app_1       | 2022-12-14T08:27:04.440Z pid=15 tid=2mr INFO: Sidekiq 7.0.2 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://redis:6379"}
app_1       | 2022-12-14T08:27:04.442Z pid=15 tid=2mr DEBUG: Client Middleware: Sidekiq::Batch::Client
app_1       | 2022-12-14T08:27:04.442Z pid=15 tid=2mr DEBUG: Server Middleware: Sidekiq::Batch::Server, Sidekiq::Metrics::Middleware
app_1       | 2022-12-14T08:27:04.442Z pid=15 tid=2mr DEBUG: Firing startup event
app_1       | on startup
app_1       | 2022-12-14T08:27:04.456Z pid=15 tid=2mr INFO: Cron Jobs - added job with name: ExpireReferralJob
app_1       | 2022-12-14T08:27:04.457Z pid=15 tid=a1f INFO: Sidekiq 7.0.2 connecting to Redis with options {:size=>1, :pool_name=>"default", :url=>"redis://redis:6379"}
app_1       | 2022-12-14T08:27:04.458Z pid=15 tid=a0r DEBUG: Firing heartbeat event
app_1       | 2022-12-14T08:27:04.657Z pid=15 tid=2mr INFO: Sidekiq running embedded, total process thread count: 8
app_1       | 2022-12-14T08:27:04.657Z pid=15 tid=2mr DEBUG: [nil, "DEBUGGER__::SESSION@server", "puma wrkr check", "config", "heartbeat", "scheduler", "default/processor", "scheduler"]
app_1       | [12] - Worker 0 (PID: 15) booted in 0.24s, phase: 0
app_1       | 2022-12-14T08:27:16.005Z pid=15 tid=a1f class=ExpireReferralJob jid=a2b6dee99562d8c6dc7e7faa INFO: start
app_1       | 2022-12-14T08:27:16.006Z pid=15 tid=a2n DEBUG: enqueued ExpireReferralJob: {"retry":true,"queue":"default","class":"ExpireReferralJob","args":[]}
app_1       | 2022-12-14T08:27:16.090Z pid=15 tid=a1f class=ExpireReferralJob jid=a2b6dee99562d8c6dc7e7faa INFO: ExpireReferralJob args=[]
app_1       | 2022-12-14T08:27:16.118Z pid=15 tid=a1f class=ExpireReferralJob jid=a2b6dee99562d8c6dc7e7faa DEBUG: 
```
Thank you guys!

**Comment by rromanchuk** [comment]
@eddygarcas 👍  I'm also loving embedded mode, makes total sense to me and much easier to manage. I know it's pseudo experimental, but I've had zero "real" issues to date.
